### ISSUE TITLE
Sometimes the Panel stays empty

### ISSUE THREAD

**Issue by JanGross** [suhodolskiy/twitch-extension-github#11]
Every now and then the Panel shows 0 Repositories/Stars/Follows:
![image](https://user-images.githubusercontent.com/13641301/80763069-01a44f00-8b3e-11ea-843f-14bd1aeac5eb.png)
And the console says
`Unchecked runtime.lastError: The message port closed before a response was received.`
If I come back the next day, it's randomly working again.  
Is this a known issue?

**Comment by suhodolskiy** [comment]
```
{
  errors: [
    {
      path: ['query', 'repositoryOwner', '... on User', 'pinnedRepositories'],
      extensions: {
        code: 'undefinedField',
        typeName: 'User',
        fieldName: 'pinnedRepositories',
      },
      locations: [{ line: 20, column: 10 }],
      message: "Field 'pinnedRepositories' doesn't exist on type 'User'",
    },
  ],
}
```
It turns out there have been changes in the graphql api github. I will try to solve this problem as soon as possible. Thanks @JanGross!

**Comment by chris-short** [comment]
I’m having the same issues

**Comment by suhodolskiy** [comment]
@JanGross @chris-short Fixed. The latest version is available in twitch extensions

**Comment by chris-short** [comment]
Much appreciated! Got it on our page now.

**Comment by AlexWayfer** [comment]
Now I see the same:

![image](https://user-images.githubusercontent.com/6510020/155363892-d51b7f2a-df36-412e-9cc5-a17c3c309f6b.png)

Configuration is OK.
