### ISSUE TITLE
Problem with github api connection

### ISSUE THREAD

**Issue by sygeman** [suhodolskiy/twitch-extension-github#41]
​From log: Refused to connect to 'https://api.github.com/graphql' because it violates the document's Content Security Policy.
![157114310-68380df4-9eb9-4c12-ba3b-61bfc75c327c](https://user-images.githubusercontent.com/5166731/157115226-2a06e98d-a6bf-4313-aead-383efd604191.png)

**Comment by suhodolskiy** [comment]
@sygeman Thanks! It has already been fixed and is waiting for verification by twitch

**Comment by suhodolskiy** [comment]
@sygeman The extension is working again 🎉

**Comment by sygeman** [comment]
Nice!
