### ISSUE TITLE
Check for null repo description

### ISSUE THREAD

**Issue by crashmax-dev** [suhodolskiy/twitch-extension-github#44]
https://github.com/suhodolskiy/twitch-extension-github/blob/2b60d251219cd415e91d480b9f07632b9a223899/src/components/Panel/render.ts#L40

![image](https://user-images.githubusercontent.com/15673111/170827113-b5dbba8d-bed8-4504-9e7c-5fa340c1b051.png)

**Comment by suhodolskiy** [comment]
@crashmax-dev Fixed 🙌
