### ISSUE TITLE
Incorrect Profile Prefix Displayed for Pinned Repositories from Different Accounts/Organizations

### ISSUE THREAD

**Issue by DustdevDM** [suhodolskiy/twitch-extension-github#52]
# Bug Overview:
The issue occurs when pinned repositories of the User belong to different user or organization accounts. In such cases, the profile prefix displayed for these repositories is incorrect, showing the name of the profile that pinned the repository instead of the actual account/organization name.

# Screenshots
### Github Profile:
![image](https://github.com/suhodolskiy/twitch-extension-github/assets/45263590/0a278ac7-cdfa-4faf-a686-312c4240aa87)
### Twitch Extension
![image](https://github.com/suhodolskiy/twitch-extension-github/assets/45263590/5583e97a-f84e-49b2-ac11-71f4719bfc1c)

# Steps to Reproduce:

1. Install and activate the Twitch extension on your Twitch profile.
2. On your Github profile page: pin repositories from other profiles
3. Go to the Twitch profile page where the extension is active.
5. Observe that the profile prefix for these repositories does not correspond to the respective account/organization name but instead displays the name of the profile that pinned the repository.

**Comment by suhodolskiy** [comment]
@DustinDEV2more Fixed 🙌
